use cadence_aria::cross_cutting::provider_adapter::{ProviderAdapter, ProviderAdapterError};
use cadence_aria::product::app_paths::ProductAppPaths;
use cadence_aria::product::lifecycle_store::{
    CreateStorySpecInput, CreateWorkspaceSessionInput, LifecycleStore,
};
use cadence_aria::product::models::{ProviderName, WorkspaceSessionStatus, WorkspaceType};
use cadence_aria::product::provider_workspace_runner::{
    ProviderWorkspaceRunner, WorkspaceProviderRunInput,
};
use cadence_aria::protocol::contracts::{AdapterInput, AdapterOutput, TimeoutStatus};
use serde_json::json;
use tempfile::tempdir;

#[test]
fn workspace_runner_calls_provider_and_records_version_and_review_round() {
    let root = tempdir().expect("root");
    let paths = ProductAppPaths::new(root.path().join(".aria"));
    let store = LifecycleStore::new(paths.clone());
    let story = store
        .create_story_spec(CreateStorySpecInput {
            project_id: "project_0001".to_string(),
            issue_id: "issue_0001".to_string(),
            repository_id: "repository_0001".to_string(),
            title: "会话过期提示".to_string(),
        })
        .expect("story");
    let session = store
        .create_workspace_session(CreateWorkspaceSessionInput {
            project_id: "project_0001".to_string(),
            issue_id: "issue_0001".to_string(),
            entity_id: story.id.clone(),
            workspace_type: WorkspaceType::Story,
            author_provider: ProviderName::Codex,
            reviewer_provider: ProviderName::ClaudeCode,
            review_rounds: 1,
            superpowers_enabled: true,
            openspec_enabled: true,
        })
        .expect("session");

    let runner = ProviderWorkspaceRunner::new(paths);
    let output = runner
        .run_next(
            WorkspaceProviderRunInput {
                session_id: session.id.clone(),
                user_prompt: "生成 Story Spec".to_string(),
            },
            &RecordingProvider,
        )
        .expect("run next");

    assert_eq!(
        output.session.status,
        WorkspaceSessionStatus::WaitingForHuman
    );
    assert_eq!(output.version.version, 1);
    assert!(
        output
            .version
            .markdown
            .contains("Story Spec generated by provider")
    );
    assert_eq!(output.review_round.round_index, 1);
    assert_eq!(output.review_round.author_provider, ProviderName::Codex);
    assert_eq!(
        output.review_round.reviewer_provider,
        ProviderName::ClaudeCode
    );
    assert_eq!(output.version.review_refs, vec![output.review_round.id]);
}

struct RecordingProvider;

impl ProviderAdapter for RecordingProvider {
    fn run(&self, input: &AdapterInput) -> Result<AdapterOutput, ProviderAdapterError> {
        assert!(input.prompt.contains("生成 Story Spec"));
        Ok(AdapterOutput {
            exit_code: Some(0),
            stdout: "Story Spec generated by provider".to_string(),
            stderr: String::new(),
            structured_output: Some(json!({
                "markdown": "# Story Spec\n\nStory Spec generated by provider",
                "review_result": "review passed",
                "revision_result": "revision applied"
            })),
            files_modified: Vec::new(),
            duration_ms: 12,
            timeout_status: TimeoutStatus::NotTimedOut,
        })
    }
}
