use crate::product::cadence_skills::routing_reference::RoutingReferenceContext;

include!("tests/part_01.rs");
include!("tests/part_02.rs");
include!("tests/part_03.rs");
include!("tests/part_04.rs");
include!("tests/part_05.rs");
include!("tests/part_06.rs");
include!("tests/part_07.rs");
include!("tests/part_08.rs");
include!("tests/part_09.rs");
include!("tests/part_10.rs");
include!("tests/part_11.rs");
include!("tests/part_12.rs");
include!("tests/part_13.rs");
include!("tests/part_14.rs");
include!("tests/part_15.rs");
include!("tests/part_16.rs");
include!("tests/part_17.rs");
include!("tests/part_18.rs");
include!("tests/part_19.rs");
include!("tests/part_20.rs");
include!("tests/part_21.rs");
include!("tests/part_22.rs");
include!("tests/part_23.rs");
include!("tests/part_24.rs");
include!("tests/part_25.rs");
include!("tests/part_26.rs");
include!("tests/part_27.rs");
include!("tests/part_28.rs");
include!("tests/part_29.rs");
include!("tests/part_30.rs");
include!("tests/part_31.rs");
include!("tests/part_32.rs");
include!("tests/recovery_task7.rs");
include!("tests/severity_three_tier.rs");
include!("tests/design_reviewer_boundary.rs");
include!("review/tests_policy_routing.rs");
mod author_revision_loop;
mod author_revision_review_routing;
mod review_repair_prompt;
mod single_candidate_prompt;
